import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Topo from "@/Componentes/Topo/index"
import SecaoCapa from "@/Componentes/secaoCapa";
import SecaoProdutos from "@/Componentes/SecaoProdutos"
import SecaoSobre from "@/Componentes/SecaoSobre";
import SecaoContato from "@/Componentes/SecaoContatos";
import Rodape from "@/Componentes/Rodape";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ótica Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topo/>
      <SecaoCapa/>
      <SecaoProdutos/>
      <SecaoSobre/>
      <SecaoContato/>  
      <Rodape/>     
    </>
  );
}
